function [BW,maskedImage] = segmentImageDisk(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 29-Jul-2020
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Close mask with disk
radius = 2;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Clear borders
BW = imclearborder(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;